### ISSUE TITLE
Duplicate "Enter" toast

### ISSUE THREAD

**Issue by arshxyz** [imsaptarshi/HacktoSearch#9]
Clicking on the input results in multiple toasts as Chakra generates a unique `id` for each toast by default. Fixing this by passing an id to the toast.

![image](https://user-images.githubusercontent.com/23417273/135348716-692da0d7-6e71-4ba0-9b08-25954dd3262f.png)

**Comment by arshxyz** [comment]
I would like to claim this issue myself, thanks.

**Comment by imsaptarshi** [comment]
> I would like to claim this issue myself, thanks.

Perfect, you're good to go!
